In [1]:
## Numpy
import numpy as np

In [3]:
lst = [1,2,3,4] 
# this is list and list convert into array
arr=np.array([lst])

In [4]:
arr

array([[1, 2, 3, 4]])

In [5]:
type(arr)
# Here find out type of array

numpy.ndarray

In [8]:
arr.shape
# Here find out the shape of array


(1, 4)

In [10]:
# Create another array
arr1=np.array([[1,2,3],[4,5,6]])

In [11]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
type(arr1)

numpy.ndarray

In [13]:
arr1.shape
# that means 2 row 3 column

(2, 3)

In [14]:
# change the shape
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
arr1.reshape(2,3)
            

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr.dtype

dtype('int32')

In [18]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1,10,2)
# Here 2 is step size taken after each digit

array([1, 3, 5, 7, 9])

In [23]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [25]:
np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [34]:
10 + np.ones((3,5))
# it is known as board cast

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [35]:
# Identity Matrix
# in identity matrix diagonal is 1 and other is 0.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
# it is just randon number generation(uniform distribution)

np.random.rand(2,3)

array([[0.07976859, 0.49935916, 0.61710756],
       [0.52798546, 0.50238279, 0.77235077]])

In [41]:
print("Random number generation")
np.random.rand(2,3)

Random number generation


array([[0.32482499, 0.37115755, 0.35311511],
       [0.6735109 , 0.22349855, 0.35901051]])

In [43]:
print("Random number following a normal distribution with mean = 0 & std = 1")

print(np.random.randn(5,3))

Random number following a normal distribution with mean = 0 & std = 1
[[ 0.78257629 -0.70039697  0.62492442]
 [-0.72715232 -1.99828461 -0.15303813]
 [-0.03632665  1.25171217  0.27796696]
 [ 0.22891702 -2.08094845  0.2608334 ]
 [-1.05045359 -2.20645168  0.59187458]]


In [49]:
# another way to create random number 
# this code show different different number between 1 to 100
np.random.randint(1,100)

47

In [60]:
arr2=np.random.randint(1,100,(4,4))

In [61]:
arr2

array([[38, 18,  3, 63],
       [ 5, 84, 24, 44],
       [35,  2, 93, 97],
       [55, 37, 74, 24]])

In [62]:
# Slicing
arr2[2:]

array([[35,  2, 93, 97],
       [55, 37, 74, 24]])

In [63]:
arr2[-1]

array([55, 37, 74, 24])

In [64]:
arr2[2:4]

array([[35,  2, 93, 97],
       [55, 37, 74, 24]])

In [80]:
arr2[2,3]

97

In [83]:
arr3=np.random.randint(2,100,20).reshape(5,4)

In [84]:
arr3

array([[54, 50, 22, 36],
       [90,  6,  3, 95],
       [ 2, 27, 67, 26],
       [ 6, 47, 75, 94],
       [47, 52, 76, 87]])

In [85]:
arr3[0:3]

array([[54, 50, 22, 36],
       [90,  6,  3, 95],
       [ 2, 27, 67, 26]])

In [86]:
arr3[0:3,0:3]

array([[54, 50, 22],
       [90,  6,  3],
       [ 2, 27, 67]])

In [87]:
arr3[3:,1:]

array([[47, 75, 94],
       [52, 76, 87]])

In [89]:
arr3[4:,1:]

array([[52, 76, 87]])

In [91]:
arr3[4:,3:]

array([[87]])

In [96]:
arr3[4:,1:,]

array([[52, 76, 87]])