In [4]:
# import the library 

import pandas as pd
import numpy as np

In [5]:
# create an array 
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
# Create a DataFrame

In [7]:
pd.DataFrame(data=np.arange(0,20).reshape(5,4))

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [8]:
# if we show columns name then write this type of code
pd.DataFrame(data=np.arange(0,20).reshape(5,4), columns=['column1', 'column2', 'column3', 'column4'])

column1  column2  column3  column4
0        0        1        2        3
1        4        5        6        7
2        8        9       10       11
3       12       13       14       15
4       16       17       18       19

In [22]:
# if we show rows name then write this type of code 
pd.DataFrame(data=np.arange(0,20).reshape(5,4), index=['row1', 'row2', 'row3', 'row4', 'row5'])

0   1   2   3
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [23]:
# if we show both columns name and rows name 
pd.DataFrame(data=np.arange(0,20).reshape(5,4), columns=['column1', 'column2', 'column3', 'column4'], index=['row1', 'row2', 'row3', 'row4', 'row5'])

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [24]:
# Here store the value in df
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4), columns=['column1', 'column2', 'column3', 'column4'], index=['row1', 'row2', 'row3', 'row4', 'row5'])

In [25]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [13]:
# type of the df
type(df)

pandas.core.frame.DataFrame

In [14]:
# Here if we show the top 5 data in dataframe
f.head()

NameError: name 'f' is not defined

In [ ]:
# Here if we show top 2 data in dataframe
df.head(2)

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7

In [ ]:
# Here if we show the tail data in data frame
df.tail()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [ ]:
# Here if we show the tail two data in dataframe
df.tail(2)

column1  column2  column3  column4
row4       12       13       14       15
row5       16       17       18       19

In [ ]:
# Here describe the data in dataframe(count,mean,std,min,max)
df.describe()

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [ ]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [ ]:
# if we show only three columns
df[['column1','column2','column3']]

column1  column2  column3
row1        0        1        2
row2        4        5        6
row3        8        9       10
row4       12       13       14
row5       16       17       18

In [ ]:
# if we show only one column
df[['column1']]

column1
row1        0
row2        4
row3        8
row4       12
row5       16

In [ ]:
# Here the type of df is DataFrame (if combine of two series that means Dataframe)
type(df[['column1']])

pandas.core.frame.DataFrame

In [ ]:
df['column1']

row1     0
row2     4
row3     8
row4    12
row5    16
Name: column1, dtype: int32

In [ ]:
# Here one clumn without column name that means series
type(df['column1'])

pandas.core.series.Series

In [ ]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [ ]:
# Here i want retieve data from raw index 1 & 3

df.loc[["row1","row3"]]

column1  column2  column3  column4
row1        0        1        2        3
row3        8        9       10       11

In [ ]:
# loc --> location
type(df.loc[['row1','row3']])

pandas.core.frame.DataFrame

In [ ]:
# whenever you don't want to use index name
# ioc--> index location

df.iloc[0:3,:]

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11

In [ ]:
df.iloc[0:3,0:2]

column1  column2
row1        0        1
row2        4        5
row3        8        9

In [ ]:
df.iloc[3:5,1:3]

column2  column3
row4       13       14
row5       17       18

In [21]:
df

A  B
0  1  1
1  2  1
2  3  1

In [ ]:
df.iloc[1:3,1:3]

column2  column3
row2        5        6
row3        9       10

In [ ]:
df.iloc[2:4,2:5]

column3  column4
row3       10       11
row4       14       15

In [ ]:
df.iloc[1:3,1:3]

column2  column3
row2        5        6
row3        9       10

In [ ]:
# if you convert in array
df.iloc[2:4,1:3].values

array([[ 9, 10],
       [13, 14]])

In [ ]:
# nan(not a number) is biscally is null values.
np.nan

nan

In [ ]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,2,3]],index=['row1',
                                                'row2'], columns=['column1',
                                                                                      'column2',
                                                                                      'colunm3'
                                                                                      ])


In [ ]:
df

column1  column2  colunm3
row1        1      NaN        2
row2        1      2.0        3

In [ ]:
# Here if null value in DataFrame is show true and other values is false
df.isnull()

column1  column2  colunm3
row1    False     True    False
row2    False    False    False

In [ ]:
# similiarly above one
df.isna().sum()

column1    0
column2    1
colunm3    0
dtype: int64

In [ ]:
# information in DataFrame
df.info

<bound method DataFrame.info of       column1  column2  colunm3
row1        1      NaN        2
row2        1      2.0        3>

In [ ]:
df['column1']

row1    1
row2    1
Name: column1, dtype: int64

In [ ]:
# find unique value
# value counts in series

df["column1"].value_counts()

column1
1    2
Name: count, dtype: int64

In [15]:
df["column1"].unique()


array([ 0,  4,  8, 12, 16])

In [16]:
df['column1'].nunique()

5

In [18]:
df=pd.DataFrame({'A': [1,2,3], 'B': [1,1,1]})

In [19]:
df.head()

A  B
0  1  1
1  2  1
2  3  1

In [26]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [27]:
df.head

<bound method NDFrame.head of       column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19>

In [28]:
df['column2']

row1     1
row2     5
row3     9
row4    13
row5    17
Name: column2, dtype: int32

In [29]:
df['column2'] > 5

row1    False
row2    False
row3     True
row4     True
row5     True
Name: column2, dtype: bool

In [31]:
df[df['column2'] > 5 ]

column1  column2  column3  column4
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [32]:
# csv --> comma sapreted values
df.to_csv('test.csv')

In [33]:
df1 = pd.read_csv("test.csv")

In [34]:
df1

Unnamed: 0  column1  column2  column3  column4
0       row1        0        1        2        3
1       row2        4        5        6        7
2       row3        8        9       10       11
3       row4       12       13       14       15
4       row5       16       17       18       19